[package]
name = "ssd1306_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics-simulator = "0.8.0"
embedded-graphics = "0.8.2"
traccam_common = { path = "../common", features = ["simulated_data"]}